"""Initial

Revision ID: 4a922b8683b6
Revises: 
Create Date: 2019-11-23 20:42:19.254235+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import application.utils.alembic_helpers as utils

# revision identifiers, used by Alembic.
revision = '4a922b8683b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Load up the pgcrypto extension so we have access to PostgreSQL-generate UUIDs
    utils.ensure_uuids_available()

    # Create our table by hand so that it automatically generates UUIDs on insert
    op.execute("""
        CREATE TABLE global_uuids(
            uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            data_type VARCHAR(64)
        )
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_uuids')
    # ### end Alembic commands ###
